export enum AppStep {
  WELCOME,
  METADATA,
  CONFIGURATION,
  CODE_INPUT,
  REVIEW,
  GENERATION
}

export enum TargetArch {
  X64 = 'x64',
  X86 = 'x86',
  ANYCPU = 'anycpu'
}

export enum OutputType {
  CONSOLE = 'exe',
  WINDOWED = 'winexe'
}

export interface ExeMetadata {
  projectName: string;
  version: string;
  author: string;
  description: string;
  copyright: string;
}

export interface ExeConfig {
  architecture: TargetArch;
  outputType: OutputType;
  frameworkVersion: string;
  iconPath?: string; // Optional path reference
  enableOptimization: boolean;
  allowUnsafe: boolean;
}

export interface BuildContext {
  metadata: ExeMetadata;
  config: ExeConfig;
  sourceCode: string; // The raw C# source
  buildLogs: string[];
}

// Initial state helpers
export const initialMetadata: ExeMetadata = {
  projectName: "MyApplication",
  version: "1.0.0.0",
  author: "Developer",
  description: "Generated by ExeForge",
  copyright: `© ${new Date().getFullYear()} All rights reserved`
};

export const initialConfig: ExeConfig = {
  architecture: TargetArch.ANYCPU,
  outputType: OutputType.CONSOLE,
  frameworkVersion: "v4.0.30319", // Standard widely available .NET
  enableOptimization: true,
  allowUnsafe: false
};
